### PR TITLE
subpages in the doc

### PR DESCRIPTION
**Pull request by philippemiron**
I played (way too long..) with autosummary this evening. It does generate a doc similar to `scipy` much easier to browse. Only thing I haven't try yet to include the figure after `chunk`.

There are also a lot of warnings when building the docs and I believe it's due to the way we import in `__init__.py` that conflicts with the `::recursive::` option.

### CODE REVIEW

**Comment by philippemiron** [comment]
image
image
image

**Comment by selipot** [comment]
WOW @philippemiron !!!

**Comment by milancurcic** [comment]
It looks awesome.

**Comment by philippemiron** [comment]
I think we should be able to create a special `_templates` for the `analysis` module and inject the `chunk` documentation, but it was not working when I tried.

**Review by milancurcic — APPROVED** [review]
Awesome, thank you. Two critical warnings had to do with wavelet.py docstrings formatting. They're gone now. The remaining warnings don't seem two concerning to me, they all seem to have to do with double definition of functions, one of them being autogenerated by Sphinx. Let's figure out where to put chunk diagram in a future PR. I built and tested the docs locally and the autosummaries work and look great.

**Comment by selipot** [comment]
What else need to be done to merge this?

**Pull request merged**
