### PR TITLE
🔧 python 3.10 upgrade

### LINKED ISSUE #335: python 3.10 upgrade
Going from 3.9 to 3.10, there were significant convenience updates to Python's typing syntax:

* Can use built-in types (`list`, `dict`, `tuple`...) for type hints rather than importing them from `typing` (`List`, `Dict`, `Tuple`)
* Using `Optional` not necessary
* `|` instead of union

For example, in Python 3.9 (our current code)

```python
from typing import Tuple, List, Optional, Union
import numpy as np
import xarray as xr

def f(
    x: Union[List, np.array, xr.DataArray],
    n: Optional[int] = 0
) -> Tuple[int, float]:
    ... 
```

becomes

```python
import numpy as np
import xarray as xr

def f(
    x: list | np.array | xr.DataArray,
    n: int = 0
) -> tuple[int, float]:
    ... 
```

The advantages are developer convenience, more concise syntax, and requiring users to use a more recent Python version.

A disadvantage is requiring users to use a more recent Python version.

### PR DESCRIPTION
**Pull request by kevinsantana11**
upgrade to python 3.10. Many of the typing changes arose from using the `pyupgrade --py310-plus` upgrade command. fixes #335

### CODE REVIEW

**Comment by philippemiron** [comment]
Looks good!

I found one more thing to modify here:

https://github.com/Cloud-Drift/clouddrift/blob/main/.github/workflows/ci.yml#L22

**Comment by kevinsantana11** [comment]
@philippemiron I see there's another PR with changes involving micro-mamba running our tests on 3.12 instead of 3.9. I pulled in one of the commits from that branch so that those changes can all be committed together unless you think its better to commit these separately

**Comment by philippemiron** [comment]
Fine either way but now it's already in this branch so I guess you can close the other one.

**Comment by philippemiron** [comment]
But I think in general we should not merge commits from others PR.

- lose attributions
- lose track of what has been changed since we do squash and merge.

**Comment by kevinsantana11** [comment]
> I think in general we should not merge commits from others PR.
> 
>     * lose attributions for the history
> 
>     * lose attributions for the release
> 
>     * lose track of what has been changed since we do squash and merge
> 
> 
> I don't really care since I've collaborated to the project already, but that could different for a new collaborator for example.

That's fair, should I remove the previous commit? Unsure if maybe we need to merge the #392 first and then this PR. If so I can create a commit reverting it.

**Comment by philippemiron** [comment]
I think if we merge the other one first, we won't have to do anything here.

**Pull request merged**
