### PR TITLE
🧹 Update random number generator in gdp1h and gdp6h adapters

### PR DESCRIPTION
**Pull request by selipot**
The code changes update the random number generator in the `gdp1h.py` and `gdp6h.py` adapters. The previous usage of `np.random.RandomState` has been replaced with `np.random.Generator(np.random.MT19937)`. This change ensures consistent and reproducible random number generation.

### CODE REVIEW

**Comment by kevinsantana11** [comment]
I think this fits with the :chore kind of commit but prefer if we use an emoji (like: 🧹) and update our CONTRIBUTING.md accordingly.

**Comment by philippemiron** [comment]
It looks like this is the new suggested way to do it. But I don't think `np.random.RandomState(42)` was incorrect.

Using:
```
python -c "import numpy as np; rng = np.random.RandomState(42); print(rng.random(10))"
```
or 
```
python -c "import numpy as np; rng = np.random.Generator(np.random.MT19937(42)); print(rng.random(10))"
```
both returns the same _random_ numbers.

**Comment by selipot** [comment]
I agree it returns the same but i read that RandomState will be deprecated. Not a big deal we don't have to change.

**Review by kevinsantana11 — APPROVED** [review]
I think its good to get out ahead of any deprecation efforts, lets merge this in

**Pull request merged**
