### PR TITLE
sofar dataset

### PR DESCRIPTION
**Pull request by philippemiron**
Not sure if this link is being update since I couldn't find anything online linking to it except Milan's notebook and other notebooks on the same repo, https://github.com/sofarocean/spotter-data-archive/blob/main/examples/.

### CODE REVIEW

**Comment by milancurcic** [comment]
Thank you for this PR. Does it need to be brought even with `main`? There are past unrelated commits.

For the function name, I suggest `spotters`.

I recommend holding with this PR until we get a thumbs up from upstream.

**Comment by philippemiron** [comment]
I don't understand, it is showing changes from previous things that are already merge. For example, if you look at `adapters/gdp` it says there is a change from `.dims -> `.sizes`, but this is already on the main branch.

**Comment by milancurcic** [comment]
Right, I can't say I understand it either :joy:

**Comment by selipot** [comment]
@isabelhoughton would you like to chime in on this PR? We are ready to add a dataset accessor for the spotter dataset into clouddrift.

**Comment by isabelhoughton** [comment]
Thanks for sharing - looks good to me. Not many sources point to https://github.com/sofarocean/spotter-data-archive/blob/main/examples/ yet as we're in the final steps of setting it all up. Let me know if any testing on my end would be appreciated.

**Comment by philippemiron** [comment]
Quick question, what is the plan with regards to update to the archive dataset? Is it to always keep the same link or create a new one each time?

**Comment by isabelhoughton** [comment]
We will create a new one each time most likely. We have not been able to sort out a DOI yet, but we would like it to be clear which version of the dataset is referred to externally.

**Comment by philippemiron** [comment]
> We will create a new one each time most likely. We have not been able to sort out a DOI yet, but we would like it to be clear which version of the dataset is referred to externally.

Ok. Once this is in place, we could add logic in the code to look for the latest available archive. For now, I just hardcoded the current link.

**Pull request merged**
