### PR TITLE
signal module

### PR DESCRIPTION
**Pull request by selipot**
PR to replace the anatrans PR. Changed the name of module to signal and implemented Milan's suggestions

### CODE REVIEW

**Comment by selipot** [comment]
Should it be expanded to multi-dimensional arrays following velocity_from_position as an example?

**Comment by milancurcic** [comment]
I think yes if it's a low-hanging fruit. `np.fft.fft` accepts `axis` to specify the axis on which to run the FFT, and slices can use the `[..., :]` syntax to indicate any number of slow-moving dimensions.

**Comment by selipot** [comment]
> I think yes if it's a low-hanging fruit. `np.fft.fft` accepts `axis` to specify the axis on which to run the FFT, and slices can use the `[..., :]` syntax to indicate any number of slow-moving dimensions.

Should I work on the multi-dimensional option in a subsequent PR?

**Review by milancurcic — APPROVED** [review]
I think this can go ahead, pending the addition of `signal` to the API docs, and also importing it in `clouddrift/__init__.py`, like the other submodules.

**Comment by selipot** [comment]
Anything else? Some version bump?

**Pull request merged**
