### PR TITLE
🐛 fix mosaic dataset bug, using empty buffers

### LINKED ISSUE #379: Mosaic datasets is broken
I saw that there were no tests for the mosaic dataset. After adding:

```
    def test_mosaic(self):
        with datasets.mosaic() as ds:
            self.assertTrue(ds)
```
I see that the dataset is not built properly. I try to quickly look, but it's using Buffers and the new download class that I'm not super familiar with, so I'm just reporting here.

I thought that:
```
    buffers = [BytesIO(b"") for _ in range(len(sorted_data_urls))]
    requests = [(url, BytesIO(b""), None) for url in sorted_data_urls]
```
should be:
```
    buffers = [BytesIO() for _ in range(len(sorted_data_urls))]
    requests = [(url, buffer, None) for url, buffer in zip(sorted_data_urls, buffers)]
```
but it did not fix it.

### PR DESCRIPTION
**Pull request by kevinsantana11**
This fixes #379 the mosaic dataset bug where the data we were referencing to create the pandas data frame was empty.

### CODE REVIEW

**Comment by philippemiron** [comment]
Weird because this is what I tried .. using`zip(urls, buffers)`.. but it was not working. I guess I has something wrong..

**Comment by kevinsantana11** [comment]
> Weird because this is what I tried, using `zip(sorted_data_urls, buffers)`, but it was not working. I guess I has something wrong..

That should have worked, might have been missing the third part of the tuple which is None if the size isn't known before hand.

**Comment by philippemiron** [comment]
See in the issue.

```
buffers = [BytesIO() for _ in range(len(sorted_data_urls))]
requests = [(url, buffer, None) for url, buffer in zip(sorted_data_urls, buffers)]
```

I think it's actually cleaner since we don't need the index in that case.

**Comment by kevinsantana11** [comment]
> See in the issue.
> 
> ```
> buffers = [BytesIO() for _ in range(len(sorted_data_urls))]
> requests = [(url, buffer, None) for url, buffer in zip(sorted_data_urls, buffers)]
> ```
> 
> I think it's actually cleaner since we don't need the index in that case.

agreed! I want to eventually make it so the src, dst are the only things that need to be provided and then optionally the size can be passed as well.

**Comment by selipot** [comment]
@kevinsantana11 I have tested this and I was able to generate the mosaic dataset by calling `clouddrift.datasets.mosaic()` and it seems fine. Yet I was getting a lot of download errors?
 
Screenshot 2024-04-10 at 4 43 00 PM

**Comment by philippemiron** [comment]
What is the error on the right? We might be trying to download too many files in parallel from the server so the download sometimes failed. But with the retry mechanism in place, it eventually picks it up.

Also, in general it is more useful to paste the code instead of including screenshot.

**Comment by selipot** [comment]
the code is at the top of the screenshot

**Comment by philippemiron** [comment]
Again it would be faster to copy and paste (I agree this one is only ~10 characters).

I'm referring to the end of this:

```
error: HTTPSConnectionPool(host....
```

**Comment by selipot** [comment]
> Again it would be faster to copy and paste (I agree this one is only ~10 characters).
> 
> But I was referring to the end of this error code:
> 
> ```
> error: HTTPSConnectionPool(host....
> ```

Interactive session in VS Code is now closed sorry. Next time I can indeed copy paste 500 lines of error messages.

**Comment by philippemiron** [comment]
Just tried it and sadly couldn't reproduce...

```
>>> from clouddrift.datasets import mosaic
>>> ds = mosaic()
/Users/pmiron/.clouddrift/data/mosaic.nc not found; download from upstream repository.
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 216/216 [00:44<00:00,  4.91Files/s]
>>> 
```

**Comment by kevinsantana11** [comment]
Below is an example of what it will look like now if a download needs to be retried, hopefully this is clearer @selipot:

Screenshot from 2024-04-11 00-25-35

**Comment by kevinsantana11** [comment]
@selipot please review when you get a chance. This looks good to me

**Pull request merged**
