### PR TITLE
🔍 update readme, badges, social connects and CloudDrift -> clouddrift

### PR DESCRIPTION
**Pull request by kevinsantana11**
I updated the readme a bit re-organizing the badges a bit. I also includes new badges for connecting socially as well as renaming thigns from CloudDrift to clouddrift where it made sense

### CODE REVIEW

**Comment by kevinsantana11** [comment]
Take a look at [this](https://github.com/kevinsantana11/clouddrift/tree/update-readme) page to get an idea of what it will look like

**Review by philippemiron — APPROVED** [review]

**Comment by selipot** [comment]
These are good ideas. I'll propose a slightly different reorg by adding commits.

**Comment by philippemiron** [comment]
Comment: 

I like the 📚 Binders section, because even though I follow the library, I had trouble finding the examples this week to show to a colleague now that they are spread in individual reports.

**Review by selipot — APPROVED** [review]
Made some edits and I think it's good to merge.

**Pull request merged**
