### PR TITLE
🐛 fix locationtype bug in dataset

### LINKED ISSUE #492: 🐛 all `location_type` are  `True` for gdp1h 2.01
```
import clouddrift as cd
ds1 = cd.datasets.gdp1h()
 all(ds1["location_type"] == True)
```
incorrectly return `True` yet
```
ds0 = xr.open_dataset('https://noaa-oar-hourly-gdp-pds.s3.amazonaws.com/latest/gdp_v2.00.zarr',engine='zarr')
all(ds1["location_type"] == True)
```
returns `False` as expected.

This means that the `location_type variable` appears to be wrong in 2.01. This needs fixing asap.

### PR DESCRIPTION
**Pull request by kevinsantana11**
fixes #492, where the location type was found to always be `true`

### CODE REVIEW

**Comment by philippemiron** [comment]
I'm not sure how you fix it, this PR shows no changes. I would suggest we use:
```
ds.attrs.get("attributes")
```
for all of the attributes conversion. That way, if an attribute is not available, it is automatically converted to None.

**Comment by kevinsantana11** [comment]
@philippemiron sorry for the confusion, I created the PR as a place holder for now while I debug the issue. I'm trying to understand where this attribute originates and it seems so far that it is available in some of the drifter data files but not all. I'm currently analyzing the data to see which drifter files have the attribute and which ones don't. I will also include the changes you mentioned in regards to the conversion.

**Comment by philippemiron** [comment]
I think the main issue is that we are doing `ds.get("location_type")` and it should be `ds.attrs.get("location_type")`.

**Comment by selipot** [comment]
Trying now to regenerate the hourly dataset, bumping version to 2.01.1 but lots of failed requests to download

**Comment by selipot** [comment]
The same bug fix cloud be implemented for `clouddrift.adapters.gdp6h()` yet it looks like the attributes of the 6 hourly netcdf files do *not* contain the `location_type` variable. This might be deduced from the string `BuoyTypeSensorArray` which should contain the letter `G` but it is not foolproof. I think we should discuss with the DAC.

**Comment by selipot** [comment]
I get the following error when filling out the array after download:
```

File /opt/homebrew/Caskroom/mambaforge/base/envs/clouddrift/lib/python3.12/site-packages/xarray/backends/api.py:552, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)
    549     kwargs.update(backend_kwargs)
    551 if engine is None:
--> 552     engine = plugins.guess_engine(filename_or_obj)
    554 if from_array_kwargs is None:
    555     from_array_kwargs = {}

File /opt/homebrew/Caskroom/mambaforge/base/envs/clouddrift/lib/python3.12/site-packages/xarray/backends/plugins.py:197, in guess_engine(store_spec)
    189 else:
    190     error_msg = (
    191         "found the following matches with the input file in xarray's IO "
    192         f"backends: {compatible_engines}. But their dependencies may not be installed, see:\n"
    193         "https://docs.xarray.dev/en/stable/user-guide/io.html \n"
    194         "https://docs.xarray.dev/en/stable/getting-started-guide/installing.html"
    195     )
--> 197 raise ValueError(error_msg)

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
```

**Comment by selipot** [comment]
I finally managed to make things work by adding `engine="netcdf"` but I am not sure it is the real reason why it works now

**Comment by kevinsantana11** [comment]
@selipot Philippe pushed the change that fixes this and I added a test ensuring the values are correct. The engine issue is separate.

**Comment by selipot** [comment]
> @selipot Philippe pushed the change that fixes this and I added a test ensuring the values are correct. The engine issue is separate.

Really, what was it?

**Comment by kevinsantana11** [comment]
The issue here was related to the following line: 
```
[False if ds.get("location_type") == "Argos" else True],
```
[source](https://github.com/Cloud-Drift/clouddrift/blob/main/clouddrift/adapters/gdp1h.py#L215)

`ds.get("location_type")` would return None for each drifter since the actual value for the `location_type` was correctly retrieved using `ds.attrs.get("location_type")` [as mentioned by Philippe](https://github.com/Cloud-Drift/clouddrift/pull/494#issuecomment-2240819428).

This is likely a result of some xarray API change since this code hasn't changed for a while and I believe the previous version of the aggregate dataset (v2.00) was generated successfully with the correct `location_type` values.

**Comment by selipot** [comment]
Yes, I pushed that commit following @philippemiron 's comment. But could not complete the re-generation of the entire array until this morning

**Comment by kevinsantana11** [comment]
@selipot got it, I'm also working on another PR that will surround all of our dependency interfacing code (requests to external servers) with some robust retry logic.

**Pull request merged**
