### PR TITLE
Awkward v2

### LINKED ISSUE #55: Upgrade to awkward v2
Awkward v2 was released on [Dec 9](https://github.com/scikit-hep/awkward/releases/tag/v2.0.0). As we don't require `<2` for `awkward` in pyproject.toml `dependencies` field, the `awkward` import will need to change from

```python
import awkward._v2 as ak
``` 

to

```python
import awkward as ak
```

and require `awkward>=2.0.0` in pyproject.toml.

Thanks to Ibis Gonzalez for reporting.

### PR DESCRIPTION
**Pull request by philippemiron**
Fix #55

### CODE REVIEW

**Comment by milancurcic** [comment]
Thanks. It looks like we got two same PRs at the same time (#58). Any preference on not changing the dependency version for awkward (my PR) vs changing it (your PR)?

**Comment by milancurcic** [comment]
@selipot will postpone the release for tomorrow while waiting for more info.

**Comment by selipot** [comment]
More info from? I do not understand the difference for the dependency so please decide.

**Comment by philippemiron** [comment]
@milancurcic only thing is that with 1.9.0 then `.to_packed()` will not work.. So I'm not sure if the try/except import is that useful.

**Comment by milancurcic** [comment]
Ah, if only I saw your response a minute earlier. That's a good reason to not allow 1.9+.

**Comment by milancurcic** [comment]
I reverted #58 with #59 and will merge this one instead.

**Comment by milancurcic** [comment]
Thanks again, @philippemiron. For future PRs, let's all please use branches in our own forks rather than in cloud-drift/clouddrift, to keep this repo clean.

**Pull request merged**
