### PR TITLE
🔍 Documentation update

### PR DESCRIPTION
**Pull request by selipot**
I thought the landing page of the documentation needed a refresh. Please let me know what you think

### CODE REVIEW

**Comment by philippemiron** [comment]
Comment: You added a breakpoint at the end of each line. I'm wondering if this introduces a line change on the website. If this is the case, it might cause problems when looking at the website on a large/small display.

**Review by philippemiron — APPROVED** [review]

**Comment by selipot** [comment]
What is the way again to visualize the documentation altered by my changes? Do I have to compile locally?

**Comment by philippemiron** [comment]
Yep, https://github.com/Cloud-Drift/clouddrift/blob/main/CONTRIBUTING.md#building-documentation-locally.

**Comment by selipot** [comment]
> Yep, https://github.com/Cloud-Drift/clouddrift/blob/main/CONTRIBUTING.md#building-documentation-locally.

Thanks! I think our library has gone to such a level that I cannot keep track anymore.

**Comment by kevinsantana11** [comment]
> > Yep, https://github.com/Cloud-Drift/clouddrift/blob/main/CONTRIBUTING.md#building-documentation-locally.
> 
> Thanks! I think our library has gone to such a level that I cannot keep track anymore.

I wonder a bit if maybe we could make this a bit easier. One way I could think of is to add a `Launch Configuration` (VS Code specific config) that has a configuration for each of our project tasks: like `building`, `testing` formatting`, `linting`, `generate-docs`, etc...

**Comment by philippemiron** [comment]
> > Yep, https://github.com/Cloud-Drift/clouddrift/blob/main/CONTRIBUTING.md#building-documentation-locally.
> 
> Thanks! I think our library has gone to such a level that I cannot keep track anymore.

At least, every time it happens we can make sure things are properly documented! :D

**Comment by selipot** [comment]
I am trying to build the documentation locally following the instructions and I am getting this error. Any clue?

```
selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ make html
Running Sphinx v7.2.6
making output directory... done
[autosummary] generating autosummary for: api.rst, datasets.rst, index.rst, install.rst, usage.rst

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x107404ea0> for event 'builder-inited' threw an exception (exception: no module named clouddrift.adapters)
make: *** [html] Error 2
selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ ls ..
CONTRIBUTING.md                 clouddrift                      ellipse_test.py                 output2.png                     test_function.py
LICENSE                         debug_output_alicanto.txt       environment.yml                 pyproject.toml                  tests
README.md                       docs                            make_ragged.py                  scratch.py                      transfer_examples.py
selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ ls ../clouddrift/
__init__.py     _version.py     datasets.py     pairs.py        ragged.py       signal.py       transfer_kpp.py
__pycache__     adapters        kinematics.py   plotting.py     raggedarray.py  sphere.py       wavelet.py
selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ 
```

**Comment by kevinsantana11** [comment]
> I am trying to build the documentation locally following the instructions and I am getting this error. Any clue?
> 
> ```
> selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ make html
> Running Sphinx v7.2.6
> making output directory... done
> [autosummary] generating autosummary for: api.rst, datasets.rst, index.rst, install.rst, usage.rst
> 
> Extension error (sphinx.ext.autosummary):
> Handler <function process_generate_options at 0x107404ea0> for event 'builder-inited' threw an exception (exception: no module named clouddrift.adapters)
> make: *** [html] Error 2
> selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ ls ..
> CONTRIBUTING.md                 clouddrift                      ellipse_test.py                 output2.png                     test_function.py
> LICENSE                         debug_output_alicanto.txt       environment.yml                 pyproject.toml                  tests
> README.md                       docs                            make_ragged.py                  scratch.py                      transfer_examples.py
> selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ ls ../clouddrift/
> __init__.py     _version.py     datasets.py     pairs.py        ragged.py       signal.py       transfer_kpp.py
> __pycache__     adapters        kinematics.py   plotting.py     raggedarray.py  sphere.py       wavelet.py
> selipot@UM-LYXV49RHY5:~/projects.git/clouddrift/docs $ 
> ```

Make sure to have installed the clouddrift library (you need to build it first, more info [here](https://github.com/Cloud-Drift/clouddrift/blob/main/CONTRIBUTING.md#building-locally-and-installing). Alternatively with the new vscode tasks I've added to the project you can do this with **one click**. see video:

[Screencast from 04-12-2024 02:27:34 PM.webm](https://github.com/Cloud-Drift/clouddrift/assets/25229837/e0a36ae1-aeec-4f4d-811e-a8fa4bed57e2)

**Comment by philippemiron** [comment]
I don't remember having to manually build install wheels like this... I did the following:

from `clouddrift/docs/`

```
conda create -n test   
conda activate test  
conda install clouddrift
pip install -r requirements.txt
make html
```

and it completed fine. So, I think as long as you have `clouddrift` install in the current environment it should work.

**Comment by selipot** [comment]
If @kevinsantana11 you see the new text looks good after building the documentation please merge.

**Comment by kevinsantana11** [comment]
> I don't remember having to manually build install wheels like this... I did the following:
> 
> from `clouddrift/docs/`
> 
> ```
> conda create -n test   
> conda activate test  
> conda install clouddrift
> pip install -r requirements.txt
> make html
> ```
> 
> and it completed fine. So, I think as long as you have `clouddrift` install in the current environment it should work.

Here I build and install the package locally so that it uses the local version of the library instead of the latest `clouddrift` distribution package in the PYPI repository. I do this because I'm fairly certain the site generation process uses the defined code and the docstrings defined in the installed library to generate parts of the documentation.

I think so long as your only testing changes in the `docs` folder the method you mentioned above will work.

**Comment by philippemiron** [comment]
OK, I see why you did it like this.

But if you look at the documentation's CI, it is only updated when a new version is released. We did it this way so we don't have online documentation that does not represent the library's current API if someone installs it from `pypi`/`conda-forge`. So, in the end, using the latest package should probably be the way to test it.

**Comment by kevinsantana11** [comment]
> OK, I see why you did it like this.
> 
> But if you look at the documentation's CI, it is only updated when a new version is released. We did it this way so we don't have online documentation that does not represent the library's current API if someone installs it from `pypi`/`conda-forge`. So, in the end, using the latest package should probably be the way to test it.

I recently made a change to how this worked where we build the package in the action and install the .whl file to the environment generating the docs.

I'm not sure how we would go about testing/inspecting the doc generation against local code changes to the library without installing a local build of the clouddrift package.

**Pull request merged**
