### PR TITLE
add option to subset and return complete_traj

### LINKED ISSUE #296: Subset improvements
Add a parameter `complete_trajectory` to return the full trajectories matching the criterion.

For example, to return trajectories that pass through the Straits of Florida. Right now, it can only "cut" trajectories inside a box.

### PR DESCRIPTION
**Pull request by philippemiron**
Fix #296

### CODE REVIEW

**Comment by selipot** [comment]
Love it! (but still need to test)

**Comment by selipot** [comment]
Here is an interesting behavior, the following code leads to the figures below. Could you reproduce?
```
from clouddrift.datasets import gdp1h
from clouddrift.ragged import subset
from clouddrift.plotting import plot_ragged
import matplotlib.pyplot as plt

ds = gdp1h()
ds1 = subset(ds, {"lat": (25, 27), "lon": (-78, -81)}, full_trajectories=True)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
plot_ragged(ax, ds1.lon, ds1.lat, ds1.rowsize, colors=np.arange(len(ds1.rowsize)));

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
time = [v.astype(np.int64) / 86400 / 1e9 for v in ds1.time.values]
plot_ragged(ax, ds1.lon, ds1.lat, ds1.rowsize, colors=np.floor(time));
```


58797a73-e44f-4c19-8940-9e93e82bb2bd

c879de40-9f64-4f78-8a09-79ce28214b18

**Comment by selipot** [comment]
> It's just a matter of fixing the axis after.
> 
> ```
> ax.set_xlim([-100, 0])
> ax.set_ylim([0, 55])
> ```

ok that was pretty dum of me ... Thanks!

**Comment by selipot** [comment]
I believe in you @philippemiron

**Comment by philippemiron** [comment]
We can see a good example of who to debug when you have no idea what's happening. haha.

**Comment by philippemiron** [comment]
I think it's finally good now. It was _correctly_ failing when tests were failing.

**Pull request merged**
