### PR TITLE
63 function to recast longitude values 0360 or 180180

### LINKED ISSUE #63: Function to recast longitude values [0,360] or [-180,180]
lon = longitude_unwrap(lon,pivot=[180,360]) : recast longitudes in [-180,180[ or or [0,360[
See in jLab deg180.m, deg360.m and inversion degunwrap.m

### PR DESCRIPTION
**Pull request by philippemiron**
First draft of the recast longitude function (Fix #63). Let me know what you think and what we should modify.

### CODE REVIEW

**Review by selipot — APPROVED** [review]
Can't test right now but are the range/intervals open or closed? i.e. is recast_longitude(-180,-180) = -180 or 180?

**Comment by philippemiron** [comment]
recast_longitude(-180,-180) = -180, I guess this is the expected behavior?

**Comment by selipot** [comment]
I think that's an acceptable behavior. I see that jlab `deg180(-180)=180` but I don't think there's a wrong or right answer here.

I reallylike the `sphere` module name. 

Thank you @philippemiron !

**Comment by selipot** [comment]
Should we have included for `recast_longitude` an optional argument specifying the dimension over which to apply? Should we set this to be a default for all subsequent functions?

**Comment by milancurcic** [comment]
I think in general we should, but it doesn't apply here because the function is element-wise.

**Pull request merged**
