### PR TITLE
`gdp.to_raggedarray`

### PR DESCRIPTION
**Pull request by milancurcic**
Implement a function `gdp.to_raggedarray` that is a convenience wrapper of executable code from the GDP hourly example.

`clouddrift.adapters.gdp.to_raggedarray()` can now be used to generate the ragged array NetCDF from hourly individual files.

Also bumped version to 0.5.0.

Not adding this to the Sphinx docs as its not intended for users. Is that reasonable? We can add this module to the API docs if you think it would be useful.

### CODE REVIEW

**Comment by selipot** [comment]
Could this type of function systematically include an example usage in the help? is that common/good practice?

**Comment by milancurcic** [comment]
I generally like examples in docstrings. I think it's a matter of style. For example, here's an examples section for `help(np.diff)`:

```
    Examples
    --------
    >>> x = np.array([1, 2, 4, 7, 0])
    >>> np.diff(x)
    array([ 1,  2,  3, -7])
    >>> np.diff(x, n=2)
    array([  1,   1, -10])
    
    >>> x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])
    >>> np.diff(x)
    array([[2, 3, 4],
           [5, 1, 2]])
    >>> np.diff(x, axis=0)
    array([[-1,  2,  0, -2]])
    
    >>> x = np.arange('1066-10-13', '1066-10-16', dtype=np.datetime64)
    >>> np.diff(x)
    array([1, 1], dtype='timedelta64[D]')
```

Xarray also includes examples in docstrings for some functions, though not all.

I'm in favor of it.

**Comment by selipot** [comment]
Yes, that is great. Let's incorporate those systematically, if possible.

**Comment by milancurcic** [comment]
Cool. I'll add examples for this function in this PR, and examples for the rest of the library in a separate PR.

**Comment by milancurcic** [comment]
Will add examples to the docstrings in a separate PR and merge this as is. Thanks all.

**Pull request merged**
