### PR TITLE
Rename vars instead of setting coords in GDP preproc

### PR DESCRIPTION
**Pull request by milancurcic**
Addresses https://github.com/Cloud-Drift/clouddrift/pull/88#issuecomment-1411421409

### CODE REVIEW

**Comment by milancurcic** [comment]
@philippemiron do you understand why black in CI thinks the analysis.py file should be reformatted? My local black is happy with it. I updated to the latest version. Sometimes this lint job is more annoying than helpful.

**Comment by philippemiron** [comment]
Yes, I understood after 1h yesterday.. check #97.

**Comment by milancurcic** [comment]
It seems to me like this is different. In this PR:

* My local black is happy with the files as they are;
* The CI black wants to format clouddrift/analysis.py (based on the log it seems like it wants to remove empty lines).

In #97, black seems to fail after being happy to not format dataformat.py and haversine.py?

**Comment by philippemiron** [comment]
I get the same error with any combinations of at least 2 files. But you are right, the output message is not the same on the Github actions.

**Pull request merged**
