### PR TITLE
🐛 fix the andro datasets

### PR DESCRIPTION
**Pull request by philippemiron**
There is a new "Quality controlled" datasets available (https://www.seanoe.org/data/00360/47077/) and the Data Release from 2022 is not available anymore. So we were querying an empty page.

### CODE REVIEW

**Comment by philippemiron** [comment]
Note that I forgot to update the docstring.

**Comment by kevinsantana11** [comment]
This change looks good to me. Only thing I can see that would also help us catch any future changes here with our CI would be to add some assertion in the test for the andro dataset function in regards to the data contained (maybe we can check variable lengths > 0). I can add this in tomorrow just to bolster our testing.

**Comment by philippemiron** [comment]
I agree adding some type of test could be good. But the dataset was return with garbage with the other url.. so not sure if just len(vars) > 0 would be enough.

**Comment by philippemiron** [comment]
Let's merge and release a new version?

**Comment by selipot** [comment]
Sure

**Pull request merged**
