### PR TITLE
Implement `RaggedArray.from_xarray()`

### LINKED ISSUE #44: Implement `RaggedArray.from_xarray()`
As discussed with @selipot on 10/20, it's in scope for clouddrift to allow getting a `RaggedArray` instance from an `xarray.Dataset`. 

`RaggedArray.from_netcdf()` already does this internally, i.e.:

https://github.com/Cloud-Drift/clouddrift/blob/437c0e4d8885d1ed4aeb08775b3dc41a7473f871/clouddrift/dataformat.py#L78-L97

Some assumptions are currently needed for the dimension names (currently assumed "traj" and "obs"). The method should allow the user to specify dimension names to use, in absence of an established convention.

### PR DESCRIPTION
**Pull request by milancurcic**
* [x] Implementation
* [x] Test
* [x] Docs

Closes #44

### CODE REVIEW

**Review by philippemiron — APPROVED** [review]
I added a test to check if the dimension names are not "traj" and "obs". Also, you can do `from clouddrift import RaggedArray` directly because `__init__.py` imports automatically the class in the `dataformat.py`.

**Comment by philippemiron** [comment]
Actually, I have two more comments to discuss:
- wouldn't it be more useful also to have the default parameters on the `from_netcdf` method? 
- we could also copy/paste this wrapper and call it `from_zarr` and it should work seamlessly

**Comment by milancurcic** [comment]
Thanks, Philippe.

On the first point, yes, it would be more useful, but I chose to leave it alone for now because we're considering removing readers and writers for file formats (parquet and netcdf). The rationale is that the users will work with data in xarray or awkward, and they can read and write from and to files from those libraries.

And similar for zarr. Most likely we'll just show the user how to do it from xarray. Less likely, you're right, it can be the same wrapper as from_netcdf.

Another reason that it wouldn't be part of this PR is that I want to keep PRs small and focused (single feature).

**Comment by milancurcic** [comment]
Thank you for the review!

**Pull request merged**
