### PR TITLE
recast longitude

### PR DESCRIPTION
**Pull request by philippemiron**
- rename function to recast_lon
- added: recast_lon180, recast_lon360 because I guess it can be useful

### CODE REVIEW

**Comment by milancurcic** [comment]
Why not also update the implementation as per https://github.com/Cloud-Drift/clouddrift/issues/121#issuecomment-1437781149? If it indeed works, it's super concise and allows us to remove the `rot` thing.

I don't think adding separate functions for specific values of an argument (e.g. `recast_lon360(lon)` vs. `recast_lon(lon, 360)`) is a good idea because it increases the surface area of the API, and the number of tests, for no meaningful gain. But if you and @selipot think it's useful, I don't oppose it, only recommend against it.

**Comment by selipot** [comment]
> Why not also update the implementation as per [#121 (comment)](https://github.com/Cloud-Drift/clouddrift/issues/121#issuecomment-1437781149)? If it indeed works, it's super concise and allows us to remove the `rot` thing.
> 

We can implement it as in  [#121 (comment)](https://github.com/Cloud-Drift/clouddrift/issues/121#issuecomment-1437781149). The current implementation is based on jlab and the matlab expectation that the function `unwrap` takes only radian as an input, hence the use of complex exponential. The numpy version of `unwrap` does not only take radian input hence the possible simpler implementation. Let's do it. 

> I don't think adding separate functions for specific values of an argument (e.g. `recast_lon360(lon)` vs. `recast_lon(lon, 360)`) is a good idea because it increases the surface area of the API, and the number of tests, for no meaningful gain. But if you and @selipot think it's useful, I don't oppose it, only recommend against it.

I want them, I use them all the time. `recast_lon360` is actually `recast_lon(lon,0)`. I don't think we have to worry about the surface area of the API at the moment.

**Comment by milancurcic** [comment]
Sounds good. Let's update the implementation, add tests for the two new functions, and expand the docstrings before merging. Since the previous implementation is already in main, let's wait for this PR before releasing 0.7.0.

**Comment by milancurcic** [comment]
1.0 is so far beyond the horizon that I don't worry about it. I could go at depth why short and frequent release cycles are good.

**Comment by milancurcic** [comment]
This is in good shape now so I'll go ahead and merge. Thanks, all!

**Pull request merged**
