### PR TITLE
Haversine_to_sph

### LINKED ISSUE #194: Fold functions in haversine.py into sphere.py
Proposed by @selipot in https://github.com/Cloud-Drift/clouddrift/pull/193#discussion_r1238785831

### PR DESCRIPTION
**Pull request by philippemiron**
Fix #194

### CODE REVIEW

**Comment by philippemiron** [comment]
This branch was initialized from the threads_,or_process branch instead of the main. I think the easiest is to first merge that PR.

**Comment by milancurcic** [comment]
Thanks for this PR @philippemiron. Do you mind opening a new PR from a feature branch based off main so that it doesn't include the commits from #198? It will make it easier to review and merge this one. Thank you!

**Comment by philippemiron** [comment]
I tried in #204 and now it looks like my main was not even up-to-date. I'll try to fix this evening.

**Comment by philippemiron** [comment]
See #205.

**Pull request closed without merging**
